# Base configs
baseurl: ""
url: "http://filipeposteral.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Filipe Posteral"
subtitle: "See the world through my eyes!"
author: "Filipe Posteral"
bio: "I am a computer engineer and a tech aficcionado from Brazil currently based in Paris."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/filipe.posteral"
  instagram: "https://www.instagram.com/posteral"
  linkedin: "https://in.linkedin.com/in/filipeposteral"
  github: "https://www.github.com/posteral"
  